In [5]:
import spacy

In [1]:
import pandas as pd

In [3]:
import tensorflow_hub as tf

/home/shohag-rana/Study/NLP/Natural-Language-Processing/tensorflow_env/lib/python3.11/site-packages/tensorflow_hub/__init__.py:61: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version


In [4]:
import tensorflow_text as text

In [5]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [6]:
model_preprocess =tf.KerasLayer(preprocess_url)

2026-08-14 23:31:39.901800: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [7]:
text = ["what you do Today can improve all your tomorrows" ,"I was born to be Awesome not perfect"]

In [8]:
reselt_preprocess =model_preprocess(text)

In [9]:
reselt_preprocess.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [ ]:
reselt_preprocess["input_type_ids"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [11]:
reselt_preprocess["input_word_ids"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  2054,  2017,  2079,  2651,  2064,  5335,  2035,  2115,
         4826,  2015,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [12]:
reselt_preprocess["input_mask"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [13]:
model_encode =tf.KerasLayer(encoder_url)

In [16]:
result_encode =model_encode(reselt_preprocess)

In [17]:
result_encode.keys()

dict_keys(['encoder_outputs', 'pooled_output', 'default', 'sequence_output'])

In [19]:
result_encode["sequence_output"]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.37176067, -0.06905239,  0.09873763, ..., -0.28248546,
          0.26766908, -0.07418426],
        [-0.04008998, -0.20619479, -0.3638038 , ..., -0.71422154,
          0.5935503 , -0.48582548],
        [ 0.2756937 , -0.26073262,  0.35446936, ..., -0.4070564 ,
          0.5713115 , -0.41308153],
        ...,
        [ 0.16786222, -0.33662245,  0.5492154 , ...,  0.3248673 ,
         -0.04241942, -0.46304125],
        [ 0.30658522, -0.06385719,  0.48186928, ...,  0.19725439,
         -0.08132666, -0.27332717],
        [ 0.36925006, -0.03721165,  0.44579846, ...,  0.10572711,
         -0.15613988, -0.21902245]],

       [[ 0.118339  ,  0.051665  , -0.22858286, ..., -0.2995642 ,
          0.4698823 ,  0.29967576],
        [ 0.10768073,  0.12255722, -0.08155975, ..., -0.5940768 ,
          0.9473216 ,  0.08126811],
        [ 0.06731689, -0.1793384 , -0.01010349, ...,  0.29826272,
          0.5805159 ,  0.49591127],
        ...,